name: build

on:
  workflow_dispatch:
    inputs:
      ref:
        description: github.com/moby/moby ref
        required: true
        type: string

env:
  DESTDIR: ./build

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120 # guardrails timeout for the whole job
    steps:
      - 
        name: Checkout moby/moby
        uses: actions/checkout@v4
        with:
          repository: moby/moby
          ref: ${{ inputs.ref }}
      -
        name: Special Platforms
        run: |
          cat >> docker-bake.hcl <<'EOF'
          target "all-linux" {
            inherits = ["all"]
            platforms = [
              "linux/amd64",
              "linux/arm64",
            ]
          }
          EOF
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build
        uses: docker/bake-action@v5
        with:
          targets: all-linux
      -
        name: List artifacts
        run: |
          tree -nh ${{ env.DESTDIR }}
      -
        name: Check artifacts
        run: |
          find ${{ env.DESTDIR }} -type f -exec file -e ascii -- {} +
      - 
        name: Package
        run: |
          REF="${{ inputs.ref }}"
          SAFE_REF="${REF//\//-}"
          tar -C build -czf "docker-${SAFE_REF}.tgz" .
      - 
        name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: docker-tgz
          path: docker-*.tgz
          if-no-files-found: error
